### ISSUE TITLE
Is project still active?

### ISSUE THREAD

**Issue by maoo** [finos/CatchIT#10]
Hi @HelloKay27 !

I see that there haven't been updates on this repo since a long time; is it still used/relevant, or shall we archive it?

Thanks in advance!

**Comment by TheJuanAndOnly99** [comment]
After talking with the CatchIT team we have decided not to archive the project and to take action on the following:
- CatchIT team to revise and [update documentation/readme](https://github.com/finos/CatchIT/blob/main/README.md).
- CatchIT team to contribute new features ~ Q3 2023.
- CatchIT team to look at and compare CatchIT to GitHub's [secret scanning alerts](https://github.blog/2023-02-28-secret-scanning-alerts-are-now-available-and-free-for-all-public-repositories/) integration.
- Start thinking about OSFF in November and the potential for a demo.
- FINOS to gather health metrics around CatchIT.

Thanks again and feel free to add anything I may have missed.
